name: GitHub profile 3D contrib

on:
  schedule:
    - cron: "2 * * * *" # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # ensures push works with GITHUB_TOKEN

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Pull latest changes
        id: git-pull
        run: |
          git pull origin main
      - name: Commit & Push
        run: |
          git commit -m "generated" || echo "No changes to commit"
          git push origin main || echo "Push failed"
