name: GitHub profile 3D contrib

on:
  schedule:
    - cron: "2 * * * *" # Every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # ensures push works with GITHUB_TOKEN

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          set -o errexit
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config --global pull.rebase true
          git stash || echo "Nothing to stash"
          git pull --rebase origin main || echo "Rebase pull failed"
          git stash pop || echo "Nothing to pop or conflict occurred"
          git add -A .
          git commit -m "generated" || echo "No changes to commit"
          git push origin main || echo "Push failed"
